### ISSUE TITLE
execution problem

### ISSUE THREAD

**Issue by ydiagne** [vahdat-ab/TGRL#3]
if we write this code the file .jucm contains nothing and they say an error occur : 
actor System {
		goal Email {name = "Email notification to recommender" ; importance = 75;}
		goal EmailToStudent {name = "Email notification to student "; importance = 75;}
		
	}
	
	actor Recommender{
		softGoal Time {name = "Time saved on writing on letters "; importance = 50;}
	    softGoal UserName {name= "UserName & password remembered"; importance = 75;}
		
	} 
	
	actor Student {
		softGoal ProgressTraceable{importance = 50;}
		softGoal MinimizeWorkload{importance = 50;}

**Comment by vahdat-ab** [comment]
Please remove "&" as a part of name for softgoal UserName. Currently, we don't support it.
You can use "and" instead of "&".

**Comment by vahdat-ab** [comment]
The issue was fixed and applied to the plugins.
