### ISSUE TITLE
problem with initial evaluation

### ISSUE THREAD

**Issue by ydiagne** [vahdat-ab/TGRL#4]
if we write the code below, in the execution of the program, they do not take into account the values written in the code :
grl StrategyBug{
	goal A;
	indicator B;
	B contributesTo A;
	strategy C{
		B= satisfied;
	}
	strategyGroup MyGroup includes C;
}

**Comment by damyot** [comment]
What you mean is that the strategy does not set the initial value of intentional element B to satisfied (whether B is an indicator or a task or a goal should not matter here).

**Comment by vahdat-ab** [comment]
The issue was resolved.

**Comment by damyot** [comment]
Seems to be working.
